config/routes.rb
Wuzazu::Application.routes.draw do
  resources :users
  resources :sessions
  resource :bets do
    collection do
      get 'new_bet'
      get 'checkout'
    end
  end
  root to: 'bets#index'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/views/layouts/_chat.html.erb
<!-- BEGIN CBOX - www.cbox.ws - v001 -->
<div id="cboxdiv" style="text-align: center; line-height: 0">
  <div><iframe frameborder="0" width="220" height="305" src="http://www4.cbox.ws/box/?boxid=4245407&amp;boxtag=503mr5&amp;sec=main" marginheight="2" marginwidth="2" scrolling="auto" allowtransparency="yes" name="cboxmain4-4245407" style="border:#ababab 1px solid;" id="cboxmain4-4245407"></iframe></div>
  <div><iframe frameborder="0" width="220" height="75" src="http://www4.cbox.ws/box/?boxid=4245407&amp;boxtag=503mr5&amp;sec=form" marginheight="2" marginwidth="2" scrolling="no" allowtransparency="yes" name="cboxform4-4245407" style="border:#ababab 1px solid;border-top:0px" id="cboxform4-4245407"></iframe></div>
</div>
<!-- END CBOX -->

app/views/layouts/_twitter.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    var yaParams = {/*Здесь параметры визита*/};
</script>

<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter22290452 = new Ya.Metrika({id:22290452,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,params:window.yaParams||{ }});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/22290452" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-7862805-26', 'wuzazu.me');
    ga('send', 'pageview');

</script>

app/views/layouts/application.html.haml
!!! 5
%html

  %head
    %title Wuzazu.me Bitcoin rock paper scissors game
    %meta{ name: 'keywords', content: "wuzazu, rock, paper, scissors, game, bitcoin" }
    %meta{ name: 'description', content: "Simple bitcoin online game. Rock-paper-scissors. Start for FREE because we give you 0.0001 BTC" }
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    - if current_user != nil
      %script{src: "http://js.pusher.com/2.1/pusher.min.js", type: "text/javascript"}
      :javascript
        // Enable pusher logging - don't include this in production
        Pusher.log = function(message) {
          if (window.console && window.console.log) {
            window.console.log(message);
          }
        };

        var pusher = new Pusher('2294b4cdc0b7996b9bf3');
        var channel = pusher.subscribe('test_channel');
        channel.bind('my_event', function(data) {
          alert(data.message);
        });

  %body


    .head_block
      .container
        .row
          .span4
            %h1
              Wuzazu.me
          .span8{style: "text-align: right;"}
            %p
              %strong
                Games:
              #{@games_stat.size + 500}
              %strong{style: "padding-left: 15px;"}
                Game cash:
              #{@games_money.round(6)} BTC

    .container
      .row
        .span9
          .game_block
            - if current_user == nil
              %h4
                Bitcoin rock-paper-scissors
              Rock-paper-scissors is a hand game usually played by two people, where players simultaneously form one of three shapes with an outstretched hand. The "rock" beats scissors, the "scissors" beat paper and the "paper" beats rock; if both players throw the same shape, the game is tied. Sign up and start to play.

              %br
              %div{style: "text-align:center; margin: 10px; font-size: 18px;"}
                %strong
                  Start for
                  %span{style: "color:#2ecc71;"} FREE
                  %br
                  because we give you 0.0001 BTC
              .info_gif
                =image_tag("info.gif")
            - if current_user != nil

              %table.table.table-bordered
                %tbody
                  %tr
                    %td.grey
                      = image_tag("r.png")
                      %br
                      Rock
                    %td.grey_1
                      = image_tag("p.png")
                      %br
                      Paper

                    %td.grey
                      = image_tag("s.png")
                      %br
                      Scissors
                %tbody
                  %tr
                    %td.grey_next
                      %a{:href => "/bets/new_bet?game_size=0&motion_type=1", class: "label label-large label-success"} BET 0.00001
                    %td.grey_1_next
                      %a{:href => "/bets/new_bet?game_size=0&motion_type=2", class: "label label-large label-success"} BET 0.00001
                    %td.grey_next
                      %a{:href => "/bets/new_bet?game_size=0&motion_type=3", class: "label label-large label-success"} BET 0.00001
                %tbody
                  %tr
                    %td.grey
                      %a{:href => "/bets/new_bet?game_size=1&motion_type=1", class: "label label-large label-success"} BET 0.0001
                    %td.grey_1
                      %a{:href => "/bets/new_bet?game_size=1&motion_type=2", class: "label label-large label-success"} BET 0.0001
                    %td.grey
                      %a{:href => "/bets/new_bet?game_size=1&motion_type=3", class: "label label-large label-success"} BET 0.0001
                %tbody
                  %tr
                    %td.grey_next
                      %a{:href => "/bets/new_bet?game_size=2&motion_type=1", class: "label label-large label-success"} BET 0.001
                    %td.grey_1_next
                      %a{:href => "/bets/new_bet?game_size=2&motion_type=2", class: "label label-large label-success"} BET 0.001
                    %td.grey_next
                      %a{:href => "/bets/new_bet?game_size=2&motion_type=3", class: "label label-large label-success"} BET 0.001
                %tbody
                  %tr
                    %td.grey
                      %a{:href => "/bets/new_bet?game_size=3&motion_type=1", class: "label label-large label-success"} BET 0.01
                    %td.grey_1
                      %a{:href => "/bets/new_bet?game_size=3&motion_type=2", class: "label label-large label-success"} BET 0.01
                    %td.grey
                      %a{:href => "/bets/new_bet?game_size=3&motion_type=3", class: "label label-large label-success"} BET 0.01
                %tbody
                  %tr
                    %td.grey_next
                      %a{:href => "/bets/new_bet?game_size=4&motion_type=1", class: "label label-large label-success"} BET 0.1
                    %td.grey_1_next
                      %a{:href => "/bets/new_bet?game_size=4&motion_type=2", class: "label label-large label-success"} BET 0.1
                    %td.grey_next
                      %a{:href => "/bets/new_bet?game_size=4&motion_type=3", class: "label label-large label-success"} BET 0.1



          = yield


        .span3
          - if current_user != nil
            %br
            %br
            .name{style: "text-align: center;"}
              Hello
              %strong
                #{wallet_hide(current_user.wallet)}
              and good luck!

            %ul.nav.nav-list.nav-list-vivid{style: "background-color: white; margin-top: 10px;"}
              %li.nav-header Statistic
              %li{style: "margin-top: 10px;"}
                All games
                %span.nav-counter #{@all_games}
              %li{style: "margin-top: 10px;"}
                Win games
                %span.nav-counter{style: "background-color: #2ecc71;"} #{@win_stat}
              %li{style: "margin-top: 10px;"}
                Lose games
                %span.nav-counter{style: "background-color: #e74c3c;"} #{@lose_stat}
              %li{style: "margin-top: 10px;"}
                Bets wait
                %span.nav-counter{style: "background-color: #f1c40f;"} #{@bets}
              %li.divider

            .sidebar{style: "background-color: #2c3e50; margin-top: 10px;"}

              %strong Your balance
              %h6{style: "color: #f4ff00;"} #{current_user.balance.round(6)} BTC
              %small
                = link_to "Logout", "/logout"

            %hr
            = render :partial => "layouts/chat"

            %br
            %a{:href => "https://coinbase.com/checkouts/df62b021b514d05901f51c701684dd0f", :target => "_blank", class: "btn btn-large btn-block btn-success btn-embossed"} Deposit
            .name{style: "text-align: center; margin: 10px;"}
              %strong NB!
              You can add bitcoins only from your profile wallet.

            %br
            %a{:href => "/bets/checkout",  class: "btn btn-large btn-block btn-info btn-embossed"} Cashout

            .name{style: "text-align: center; margin: 10px;"}
              %strong NB!
              Minimal balance to checkout = 0.001 BTC



          - if current_user == nil
            %br
            .sign_in
              = form_tag sessions_path do
                %h6 Your Wallet
                = text_field_tag :wallet, params[:wallet]
                %h6 Your password
                = password_field_tag :password
                = submit_tag "Sign in/up", class: "btn btn-large btn-block btn-success btn-embossed"
            .sidebar{style: "background-color: #34495e;"}
              %strong
                We have in-game chat

          .sidebar
            %strong
              We on
              =link_to "BitcoinTalk.org", 'https://bitcointalk.org/index.php?topic=296060.0'


          .footer
            = render :partial => "layouts/twitter"